import { Open_Sans } from 'next/font/google';
import { AuthProvider } from '../context/AuthContext';
import './globals.css';
import { cn } from '@/utils/cn';
AuthProvider;
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn('antialiased bg-bg dark:bg-bgDark', openSans.className)}
    >
      <AuthProvider>
        <body className="min-h-screen">{children}</body>
      </AuthProvider>
    </html>
  );
}
